// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.31.0
// source: face_recognition_protos/embed.proto

package face_recognition_service

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	FaceEmbedder_GetEmbedding_FullMethodName = "/embed.FaceEmbedder/GetEmbedding"
)

// FaceEmbedderClient is the client API for FaceEmbedder service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FaceEmbedderClient interface {
	GetEmbedding(ctx context.Context, in *ImageRequest, opts ...grpc.CallOption) (*EmbeddingResponse, error)
}

type faceEmbedderClient struct {
	cc grpc.ClientConnInterface
}

func NewFaceEmbedderClient(cc grpc.ClientConnInterface) FaceEmbedderClient {
	return &faceEmbedderClient{cc}
}

func (c *faceEmbedderClient) GetEmbedding(ctx context.Context, in *ImageRequest, opts ...grpc.CallOption) (*EmbeddingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EmbeddingResponse)
	err := c.cc.Invoke(ctx, FaceEmbedder_GetEmbedding_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FaceEmbedderServer is the server API for FaceEmbedder service.
// All implementations must embed UnimplementedFaceEmbedderServer
// for forward compatibility.
type FaceEmbedderServer interface {
	GetEmbedding(context.Context, *ImageRequest) (*EmbeddingResponse, error)
	mustEmbedUnimplementedFaceEmbedderServer()
}

// UnimplementedFaceEmbedderServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFaceEmbedderServer struct{}

func (UnimplementedFaceEmbedderServer) GetEmbedding(context.Context, *ImageRequest) (*EmbeddingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetEmbedding not implemented")
}
func (UnimplementedFaceEmbedderServer) mustEmbedUnimplementedFaceEmbedderServer() {}
func (UnimplementedFaceEmbedderServer) testEmbeddedByValue()                      {}

// UnsafeFaceEmbedderServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FaceEmbedderServer will
// result in compilation errors.
type UnsafeFaceEmbedderServer interface {
	mustEmbedUnimplementedFaceEmbedderServer()
}

func RegisterFaceEmbedderServer(s grpc.ServiceRegistrar, srv FaceEmbedderServer) {
	// If the following call pancis, it indicates UnimplementedFaceEmbedderServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FaceEmbedder_ServiceDesc, srv)
}

func _FaceEmbedder_GetEmbedding_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ImageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FaceEmbedderServer).GetEmbedding(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FaceEmbedder_GetEmbedding_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FaceEmbedderServer).GetEmbedding(ctx, req.(*ImageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// FaceEmbedder_ServiceDesc is the grpc.ServiceDesc for FaceEmbedder service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FaceEmbedder_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "embed.FaceEmbedder",
	HandlerType: (*FaceEmbedderServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetEmbedding",
			Handler:    _FaceEmbedder_GetEmbedding_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "face_recognition_protos/embed.proto",
}
